### ISSUE TITLE
Can tianshou be used for meta-RL setting?

### ISSUE THREAD

**Issue by KeXue-NJU** [thu-ml/tianshou#430]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [ ] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [ ] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [ ] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  ```
I want to learn a policy from some training envs and wish it can be generalized to some unseen but similar testing envs.
That is , in the definitions of envs, I have: 
  ```python
  train_envs_list = [env1,env2,env3]
  test_envs_list = [env4,env5,env6]
  train_envs = SubprocVectorEnv([lambda: MakeEnv(env_name=train_envs_list[i]) for i in range(len(train_envs_list)])
  test_envs = SubprocVectorEnv([lambda: MakeEnv(env_name=train_envs_list[i]) for i in range(len(train_envs_list)])
  ```
In these envs, they have the same state spaces and actioin spaces, but with different properties and transitions. 
Can tianshou work well for this setting?

**Comment by Trinkle23897** [comment]
The pipeline should work well but I'm not sure about the actual performance.

**Comment by KeXue-NJU** [comment]
> The pipeline should work well but I'm not sure about the actual performance.

Thanks for your reply! I'll try it out.
